using System;
using System.Collections.Generic;
using System.IO;
using Newtonsoft.Json;
using Polyrific.Catapult.Plugins.Core.Configs;
using Polyrific.Catapult.Shared.Dto.Constants;
using Polyrific.Catapult.Shared.Dto.ProjectDataModel;
using Xunit;

namespace Polyrific.Catapult.Plugins.AspNetCoreMvc.UnitTests
{
    public class CodeGeneratorProviderTests
    {
        [Fact]
        public async void Generate_Success()
        {
            var models = GetSampleDataModels();
            var outputFolderName = "20180817.1";
            var workingLocation = Path.Combine(AppContext.BaseDirectory, "working");
            var outputLocation = Path.Combine(workingLocation, outputFolderName);

            var config = new GenerateTaskConfig
            {
                WorkingLocation = workingLocation,
                OutputLocation = outputLocation
            };

            var additionalConfig = new Dictionary<string, string>();

            if (Directory.Exists(outputLocation))
                Directory.Delete(outputLocation, true);

            var provider = new Program(new string[] { GetArgString("main", "TestProject", models, config, additionalConfig) });
            var result = await provider.Generate();

            Assert.Equal(outputLocation, result.outputLocation);
            Assert.True(Directory.Exists(outputLocation));
        }

        [Fact]
        public void AddModelTag_CSharp_Success()
        {
            var models = GetSampleDataModels();
            var config = new GenerateTaskConfig();
            var additionalConfig = new Dictionary<string, string>();
            var provider = new Program(new string[] { GetArgString("main", "TestProject", models, config, additionalConfig) });

            string fileContent =
@"using System;
namespace Polyrific.Catapult.Plugins.AspNetCoreMvc
{
    public class TestModel
    {
    }
}
";
            var result = provider.AddModelTag(fileContent, GeneratedFileType.CSharp, "1");
            Assert.Equal(
@"// OpenCatapultModelId:1
using System;
namespace Polyrific.Catapult.Plugins.AspNetCoreMvc
{
    public class TestModel
    {
    }
}
", result);
        }

        [Fact]
        public void GetFileModelId_CSharp_Success()
        {
            var models = GetSampleDataModels();
            var config = new GenerateTaskConfig();
            var additionalConfig = new Dictionary<string, string>();
            var provider = new Program(new string[] { GetArgString("main", "TestProject", models, config, additionalConfig) });

            string fileContent =
@"// OpenCatapultModelId:1
namespace Polyrific.Catapult.Plugins.AspNetCoreMvc
{
    public class TestModel
    {
    }
}
";
            var result = provider.GetFileModelId(fileContent, GeneratedFileType.CSharp);
            Assert.Equal("1", result);
        }

        [Fact]
        public void AddAutoGeneratedContentTag_CSharp_Success()
        {
            var models = GetSampleDataModels();
            var config = new GenerateTaskConfig();
            var additionalConfig = new Dictionary<string, string>();
            var provider = new Program(new string[] { GetArgString("main", "TestProject", models, config, additionalConfig) });

            string fileContent =
@"using System;
namespace Polyrific.Catapult.Plugins.AspNetCoreMvc
{
    public class TestModel
    {
    }
}
";
            var result = provider.AddAutoGeneratedContentTag(fileContent, GeneratedFileType.CSharp, "testContent");
            Assert.Equal(
@"// Begin auto-generated content: testContent
using System;
namespace Polyrific.Catapult.Plugins.AspNetCoreMvc
{
    public class TestModel
    {
    }
}
// End auto-generated content: testContent
", result);
        }

        [Fact]
        public void UpdateAutoGeneratedContent_CSharp_Success()
        {
            var models = GetSampleDataModels();
            var config = new GenerateTaskConfig();
            var additionalConfig = new Dictionary<string, string>();
            var provider = new Program(new string[] { GetArgString("main", "TestProject", models, config, additionalConfig) });

            string fileContent =
@"// Begin auto-generated content: testContent
using System;
namespace Polyrific.Catapult.Plugins.AspNetCoreMvc
{
    public class TestModel
    {
    }
}
// End auto-generated content: testContent
";

            string updatedContent =
@"using System;
namespace Polyrific.Catapult.Plugins.AspNetCoreMvc
{
    public class UpdatedTestModel
    {
    }
}
";
            var result = provider.UpdateAutoGeneratedContent(fileContent, updatedContent, GeneratedFileType.CSharp, "testContent");
            Assert.Equal(
@"// Begin auto-generated content: testContent
using System;
namespace Polyrific.Catapult.Plugins.AspNetCoreMvc
{
    public class UpdatedTestModel
    {
    }
}
// End auto-generated content: testContent
", result);
        }

        private List<ProjectDataModelDto> GetSampleDataModels()
        {
            var models = new List<ProjectDataModelDto>
            {
                new ProjectDataModelDto
                {
                    Name = "Product",
                    Description = "Product",
                    Label = "Product",
                    Properties = new List<ProjectDataModelPropertyDto>
                    {
                        new ProjectDataModelPropertyDto
                        {
                            Name = "Title",
                            Label = "Title",
                            DataType = PropertyDataType.String,
                            ControlType = PropertyControlType.InputText
                        },
                        new ProjectDataModelPropertyDto
                        {
                            Name = "Price",
                            Label = "Price",
                            DataType = PropertyDataType.Integer,
                            ControlType = PropertyControlType.InputNumber
                        }
                    }
                }
            };

            return models;
        }

        private string GetArgString(string process, string projectName, List<ProjectDataModelDto> dataModels, GenerateTaskConfig taskConfig, Dictionary<string, string> additionalConfigs)
        {
            var dict = new Dictionary<string, object>
            {
                {"process", process},
                {"project", projectName},
                {"models", dataModels},
                {"config", taskConfig},
                {"additional", additionalConfigs}
            };

            return JsonConvert.SerializeObject(dict);
        }
    }
}
